---
- project:
    queue: kolla
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-jobs
      - ansible-role-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - periodic-stable-jobs
    check:
      jobs:
        - kolla-ansible-centos9s
        - kolla-ansible-debian-bullseye
        - kolla-ansible-debian-bookworm
        - kolla-ansible-openeuler
        - kolla-ansible-rocky9
        - kolla-ansible-ubuntu
        - kolla-ansible-rocky9-kvm
        - kolla-ansible-ubuntu-kvm
        - kolla-ansible-rocky9-multinode-ipv6
        - kolla-ansible-ubuntu-multinode-ipv6
        - kolla-ansible-rocky9-bifrost
        - kolla-ansible-ubuntu-bifrost
        - kolla-ansible-rocky9-zun
        - kolla-ansible-debian-bullseye-zun
        - kolla-ansible-ubuntu-zun
        - kolla-ansible-rocky9-swift
        - kolla-ansible-ubuntu-swift
        - kolla-ansible-rocky9-scenario-nfv
        - kolla-ansible-rocky9-magnum
        - kolla-ansible-ubuntu-magnum
        - kolla-ansible-rocky9-octavia
        - kolla-ansible-ubuntu-octavia
        - kolla-ansible-rocky9-masakari
        - kolla-ansible-ubuntu-masakari
        - kolla-ansible-rocky9-ironic
        - kolla-ansible-debian-bullseye-ironic
        - kolla-ansible-debian-bookworm-ironic
        - kolla-ansible-ubuntu-ironic
        - kolla-ansible-ubuntu-cells
        - kolla-ansible-rocky9-cells
        - kolla-ansible-rocky9-mariadb
        - kolla-ansible-ubuntu-mariadb
        - kolla-ansible-debian-ovn
        - kolla-ansible-rocky9-ovn
        - kolla-ansible-ubuntu-ovn
        - kolla-ansible-debian
        - kolla-ansible-rocky9-prometheus-opensearch
        - kolla-ansible-ubuntu-prometheus-opensearch
        - kolla-ansible-rocky9-venus
        - kolla-ansible-ubuntu-venus
        - kolla-ansible-rocky9-cephadm
        - kolla-ansible-ubuntu-cephadm
        - kolla-ansible-rocky9-hashi-vault
        - kolla-ansible-ubuntu-lets-encrypt
        - kolla-ansible-rocky9-lets-encrypt
    check-arm64:
      jobs:
        - kolla-ansible-debian-bullseye-aarch64
        - kolla-ansible-debian-bookworm-aarch64
    gate:
      jobs:
        - kolla-ansible-debian-bullseye
        - kolla-ansible-debian-bookworm
        - kolla-ansible-rocky9
        - kolla-ansible-ubuntu
